name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download ngrok v3
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -Outfile ngrok.zip

      - name: Extract ngrok
        run: Expand-Archive ngrok.zip

      - name: Check ngrok version
        run: .\ngrok.exe version

      - name: Auth ngrok
        run: .\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable Terminal Services
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

      - name: Enable Firewall Rule
        run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Allow RDP User Authentication
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Set Password for Runner Admin
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "zqwxas12A" -Force)

      - name: Create Tunnel
        run: .\ngrok.exe tcp 3389
